# Change these first
owner: enuves # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Aplicação Web
    url: https://app.enuves.com
  - name: Eventos
    url: https://events.enuves.com
  - name: Formulários
    url: https://forms.enuves.com
  - name: Website
    url: https://www.enuves.com
  - name: API
    url: https://api.enuves.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: Status
  introMessage: Status page for enuves website
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
